name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Run npm install
        run: npm install
      - run: npm run build

      - name: Release to PROD Branch
        uses: casperdcl/push-dir@v1
        with:
          message: update PROD
          branch: PROD
          dir: dist
          history: false
          force: true
